name: release

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm ]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://golang.org/dl/go1.15.6.linux-amd64.tar.gz"
          build_flags: "-tags nocv"
          pre_command: "go mod edit -droprequire gocv.io/x/gocv"