name: release

on:
  release:
    types: [ created ]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm ]
        exclude:
          - goos: darwin
            goarch: arm
          - goos: darwin
            goarch: "386"
    steps:
      - uses: actions/checkout@v2
      - name: Set BUILD_TIME env
        run: echo BUILD_TIME=$(date --rfc-3339=seconds) >> ${GITHUB_ENV}
      - uses: wangyoucao577/go-release-action@v1.16
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://golang.org/dl/go1.16.4.linux-amd64.tar.gz"
          build_flags: "-tags nocv"
          ldflags: -X "main.BuildTime=${{ env.BUILD_TIME }}" -X main.CommitId=${{ github.sha }}
          pre_command: "go mod edit -droprequire gocv.io/x/gocv"